---
output: html_document
---

Workshops and Conferences

•	Participated in the “Fifth National Conferences on Science and Technology” organized Nepal Academy of Science and Technology (10-12 November 2008).

•	Worked as an exhibitor in “The Second National Science Exhibition” organized by Central Department of Physics Tribhuvan University (7-10 Feb 2011).

•	Participated in the “International School of Astronomy and Space Science” organized by B.P Koirala Memorial Planetarium Observatory and Science Museum Development Board (1-10 Oct 2012).

•	Participated in the “National Workshops on Astronomy and Astrophysics” organized by Central Department of Physics, Tribhuvan University (25-28 June 2013).


•	Participated in the international workshop on “Black Holes and Friends” organized by Fudan University Shanghai, China (30 March-1 April 2015).

•	Participated in the a “Youth for Smart Solutions” conference on Climate change organized by Nepal Prakriti Pathshala (26-28 March 2014).

•	Participated in the 236th meeting of American Astronomical Society which was held on 1-3 June 2020. There I presented the poster related my work in Ph.D.

•	Participated and presented a short talk about my work in PhD in ANPA conference which was held on July 17-19.

•	Participated in the workshop of AtomDB. Which was conducted in Aug 3-5 2020.

•	Participated in all the colloquia of Western Michigan since Fall 2015 to till now.
